version: '3.9'

services:
  api:
    build:
      context: ./api
    command: gunicorn -b 0.0.0.0:8000 'app:create_app(None, True)'
    ports:
      - 8000:8000
    environment:
      FLASK_APP: app
      FLASK_ENV: production
    volumes:
      - ./api/instance/zoomies.sqlite:/api/instance/zoomies.sqlite:rw
  frontend:
    build:
      context: ./frontend
    user: nextjs
    command: npm run start
    ports:
      - 3000:3000
    environment:
      NEXT_TELEMETRY_DISABLED: 1
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: /api
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/etc/nginx/proxy_params:/etc/nginx/proxy_params:ro
      - ./certbot/var/www/certbot/:/var/www/certbot/:ro
      - ./certbot/etc/letsencrypt/:/etc/letsencrypt/:ro
    depends_on:
      - api
      - frontend
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/var/www/certbot/:/var/www/certbot/:rw
      - ./certbot/etc/letsencrypt/:/etc/letsencrypt/:rw
      - ./certbot/var/log/letsencrypt/:/var/log/letsencrypt/:rw
